export interface SurrenderFormState {
  firstName: string
  lastName: string
  phoneNumber: string
  email: string
  streetAddress: string
  city: string
  state: string
  zipCode: string
  whenToSurrenderCat: string
  catName: string
  catSex: string
  catAge: string
  catOwnershipDuration: string
  catLocationFound: string
  catWhySurrendered: string
  agesOfHouseholdMembers: string
  otherPetsInHousehold: string
  catsBehaviorTowardsKnownPeople: string
  catsBehaviorTowardsStrangers: string
  catsBehaviorTowardsKnownAnimals: string
  commentsOnBehavior: string
  catsReactionToNewPeople: string
  catHouseTrained: string
  catSpendMajorityOfTime: string
  catLeftAloneDuration: string
  catWhenLeftAlone: string
  catLeftAloneBehaviors: string
  catHowItPlays: string
  catToysItLikes: string
  catGamesItLikes: string
  catScaredOfAnything: string
  catScaredOfAnythingExplanation: string
  catBadHabits: string
  catAllowedOnFurniture: string
  catSleepAtNight: string
  catBehaviorFoodOthers: string
  catBehaviorToysOthers: string
  catProblemsRidingInCar: string
  catProblemsRidingInCarExplanation: string
  catEscapedBefore: string
  catEscapedBeforeExplanation: string
  catEverAttackedPeople: string
  catEverAttackedPeopleExplanation: string
  catEverAttackedOtherCats: string
  catEverAttackedOtherCatsExplanation: string
  catVeterinarianList: string
  catVeterinarianYearlyVisits: string
  catSpayedNeutered: string
  catVaccinationHistory: string
  catVaccinationsCurrent: string
  catTestedHeartworm: string
  catTestedHeartwormExplanation: string
  catHeartwormPrevention: string
  catHeartwormPreventionExplanation: string
  catMicrochipped: string
  catMicrochippedExplanation: string
  catVetOrGroomerBehavior: string
  catVetMuzzled: string
  catPastOrPresentHealthProblems: string
  catPastOrPresentHealthProblemsExplanation: string
  catCurrentMedications: string
  catCurrentMedicationsExplanation: string
  catTypeOfFood: string
  catEatingFrequency: string
  catAmountOfFood: string
  catFoodTreats: string
  catFoodTreatsExplanation: string
  additionalInformation: string
  fullBodyPhotoOfCat: string
  closeUpPhotoOfCatsFace: string
  copiesOfRecords: string
}
