export const CAT_BREEDS = [
  'Unknown',
  'Abyssinian',
  'Aegean',
  'American Bobtail',
  'American Curl',
  'American Polydactyl',
  'American Ringtail',
  'American Shorthair',
  'American Wirehair',
  'Aphrodite',
  'Arabian Mau',
  'Asian Hsorthair',
  'Asian Semi-Longhair',
  'Australian Mist',
  'Balinese',
  'Bambino',
  'Bengal',
  'Birman',
  'Bombay',
  'Bramble',
  'Brazilian Shorthair',
  'British Longhair',
  'British Semi-Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'California Spangled',
  'Chantilly',
  'Chartreux',
  'Chausie',
  'Cheetoh',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Coupari',
  'Cymric',
  'Desert Lynx',
  'Devon Rex',
  'Domestic Longhair',
  'Domestic Medium Hair',
  'Domestic Shorthair',
  'Donskoy',
  'Dragon Li',
  'Dwelf Cat',
  'Egyptian Mau',
  'European Burmese',
  'European Shorthair',
  'Exotic Shorthair',
  'Foldex Cat',
  'German Rex',
  'Havana',
  'Highlander',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Kashmir',
  'Khao Manee',
  'Kinkalow',
  'Korat',
  'Korean Shorthair',
  'Korn Ja',
  'Kurilian Bobtail',
  'Lambkin',
  'Laperm',
  'Lykoi',
  'Maine Coon Polydactyl',
  'Maine Coon',
  'Mandalay',
  'Manx',
  'Mekong Bobtail',
  'Minskin',
  'Minuet',
  'Munchkin',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Ojos Azules',
  'Oriental Longhair',
  'Oriental Shorthair',
  'Owyhee Bob',
  'Peke-Faced',
  'Persian',
  'Peterbald',
  'Pixiebob',
  'Raas',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Sam Sawet',
  'Savannah',
  'Scottish Fold',
  'Scottish Straight',
  'Selkirk Rex',
  'Serengeti',
  'Serrade Petit',
  'Siamese',
  'Siberian',
  'Singapura',
  'Skookum',
  'Snowshoe',
  'Sokoke',
  'Somali',
  'Sphynx',
  'Suphalak',
  'Tennessee Rex',
  'Thai',
  'Tonkinese',
  'Toybob',
  'Toyger',
  'Turkish Angora',
  'Turkish Van',
  'Ukrainian Levkoy',
  'York Chocolate',
] as const

export const DOG_BREEDS = [
  'Unknown',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Eskimo Dog',
  'American Foxhound',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'Anatolian Shepherd Dog',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Australian Terrier',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Bloodhound',
  'Border Collie',
  'Border Terrier',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Brittany',
  'Bull Terrier',
  'Bulldog',
  'Cairn Terrier',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Collie',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'English Bulldog',
  'English Setter',
  'English Springer Spaniel',
  'French Bulldog',
  'German Shepherd',
  'German Shorthaired Pointer',
  'Giant Schnauzer',
  'Golden Retriever',
  'Great Dane',
  'Great Pyrenees',
  'Havanese',
  'Irish Setter',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Keeshond',
  'Labrador Retriever',
  'Lhasa Apso',
  'Maltese',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Mixed Breed',
  'Newfoundland',
  'Norwegian Elkhound',
  'Old English Sheepdog',
  'Papillon',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Pit Bull',
  'Pointer',
  'Pomeranian',
  'Poodle',
  'Portuguese Water Dog',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Schipperke',
  'Scottish Terrier',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Soft Coated Wheaten Terrier',
  'Staffordshire Bull Terrier',
  'Standard Poodle',
  'Tibetan Mastiff',
  'Vizsla',
  'Weimaraner',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
] as const

export type TCatBreed = (typeof CAT_BREEDS)[number]
export type TDogBreed = (typeof DOG_BREEDS)[number]

export type TPetBreed = TCatBreed | TDogBreed
